In [55]:
import numpy as np

In [56]:
# 1. A teacher stores the scores of 10 students in a 1D NumPy array. Write code to display the 1D array and print scores greater than 50.

scores = np.array(list(map(int, input("Enter 10 student scores separated by space: ").split())))
print("Scores:", scores)
print("Scores > 50:", scores[scores > 50])



Enter 10 student scores separated by space: 90 100 80 40 20 89 99 29 45 75
Scores: [ 90 100  80  40  20  89  99  29  45  75]
Scores > 50: [ 90 100  80  89  99  75]


In [57]:
# 2. Using the same scores array, find the mean score of the class.

print("Mean Score:", np.mean(scores))

Mean Score: 66.7


In [58]:
# 3. Determine the median of the scores to check the central tendency.

print("Median Score:", np.median(scores))

Median Score: 77.5


In [63]:
# 4. Find the mode of the scores to identify the most frequent score.

unique, counts = np.unique(scores, return_counts=True)

# Find the index of the highest count
max_count_index = np.argmax(counts)

# The mode is the value at that index
mode_score = unique[max_count_index]

print("Mode of scores:", mode_score)

Mode of scores: 20


In [64]:
# 5. You are given a 2D NumPy array containing temperatures recorded over 4 weeks (rows) for 7 days (columns). Display the full array and the temperature of the second week.

import numpy as np

temps = []
print("Enter temperatures for 4 weeks (7 values per week):")
for i in range(4):
    week = list(map(int, input(f"Week {i+1}: ").split()))
    temps.append(week)

temps = np.array(temps)

print("Full Temperature Array:\n", temps)

second_week = temps[1]
print("Second week temperatures as array:", "[" + ", ".join(map(str, second_week)) + "]")


Enter temperatures for 4 weeks (7 values per week):
Week 1: 30
Week 2: 32
Week 3: 31
Week 4: 29
Full Temperature Array:
 [[30]
 [32]
 [31]
 [29]]
Second week temperatures as array: [32]


In [65]:
# 6. Find the highest temperature of the month using NumPy.

print("Highest Temperature:", np.max(temps))

Highest Temperature: 32


In [66]:
# 7. Normalize all temperatures using Min-Max normalization formula.

min_val = np.min(temps)
max_val = np.max(temps)
normalized_temps = (temps - min_val) / (max_val - min_val)
print("Normalized Temperatures:\n", normalized_temps)

Normalized Temperatures:
 [[0.33333333]
 [1.        ]
 [0.66666667]
 [0.        ]]


In [67]:
# 8. Calculate the standard deviation of the temperature data.

print("Standard Deviation:", np.std(temps))

Standard Deviation: 1.118033988749895


In [73]:
# 9. A supermarket tracks stock of 3 products over 4 weeks and 5 categories. Represent this using a 3D NumPy array. Write code to access stock of 2nd product in week 3.

print("Enter stock for 3 products over 4 weeks and 5 categories (60 values):")
stock_input = list(map(int, input().split()))
stock = np.array(stock_input).reshape(3, 4, 5)
print("Stock of 2nd product in week 3:\n", stock[1, 2])


Enter stock for 3 products over 4 weeks and 5 categories (60 values):
1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59 60
Stock of 2nd product in week 3:
 [31 32 33 34 35]


In [74]:
# 10. Calculate the total stock of each product over all weeks and categories.

total_stock = np.sum(stock, axis=(1, 2))
print("Total stock per product:", total_stock)

Total stock per product: [ 210  610 1010]


In [76]:
# 11. A 1D NumPy array holds survey ratings (scale of 1–10) from 50 people. Find how many people rated more than 7.

ratings = np.array(list(map(int, input("Enter 50 survey ratings (1-10 scale): ").split())))
print("People who rated > 7:", np.sum(ratings > 7))

Enter 50 survey ratings (1-10 scale): 7 8 5 6 9 10 4 6 7 8 6 5 9 7 8 6 5 4 3 9 8 7 6 5 4 7 6 8 9 10 3 2 5 6 7 8 9 6 5 4 7 6 5 8 9 4 3 7 6 5
People who rated > 7: 15


In [77]:
# 12. Count how many people gave a neutral rating (rating == 5).

print("People who gave neutral rating (5):", np.sum(ratings == 5))

People who gave neutral rating (5): 8


In [78]:
# 13. Normalize the ratings between 0 and 1.

ratings_normalized = (ratings - np.min(ratings)) / (np.max(ratings) - np.min(ratings))
print("Normalized Ratings:", ratings_normalized)

Normalized Ratings: [0.625 0.75  0.375 0.5   0.875 1.    0.25  0.5   0.625 0.75  0.5   0.375
 0.875 0.625 0.75  0.5   0.375 0.25  0.125 0.875 0.75  0.625 0.5   0.375
 0.25  0.625 0.5   0.75  0.875 1.    0.125 0.    0.375 0.5   0.625 0.75
 0.875 0.5   0.375 0.25  0.625 0.5   0.375 0.75  0.875 0.25  0.125 0.625
 0.5   0.375]


In [82]:
# 14. A fitness app stores 7 days of step count for 5 users in a 2D array. Find the average steps per user.

steps = []
print("Enter 7 days of step counts for 5 users:")
for i in range(5):
    user_steps = list(map(int, input(f"User {i+1}: ").split()))
    steps.append(user_steps)
steps = np.array(steps)
print("Average steps per user:", np.mean(steps, axis=1))

Enter 7 days of step counts for 5 users:
User 1: 284 294 102 438 275 128 248
User 2: 124 538 194 596 836 924 284
User 3: 281  238 853 218 284 473 583
User 4: 823 375 532 375 835 237 823
User 5: 237 182 538 273 583 277 283
Average steps per user: [252.71428571 499.42857143 418.57142857 571.42857143 339.        ]


In [83]:
# 15. Display the steps recorded on day 3 for all users.

print("Steps on Day 3 for all users:", steps[:, 2])

Steps on Day 3 for all users: [102 194 853 532 538]


In [84]:
# 16. Identify users who walked more than 7000 steps on any day.

users_above_7000 = np.where(np.any(steps > 7000, axis=1))[0]
print("Users who walked more than 7000 steps on any day:", users_above_7000)

Users who walked more than 7000 steps on any day: []


In [85]:
# 17. Record the results of 10 trials for 3 chemical samples using a 2D array. Calculate the mean result for each chemical.

print("Enter results of 10 trials for 3 chemicals (30 values):")
results = np.array(list(map(float, input().split()))).reshape(10, 3)
mean_results = np.mean(results, axis=0)
print("Mean result per chemical:", mean_results)

Enter results of 10 trials for 3 chemicals (30 values):
5.6 5.8 5.7 6.1 6.0 6.2 5.9 6.1 6.0 5.7 5.6 5.8 6.0 6.2 6.1 5.8 5.9 5.7 6.1 6.0 6.3 5.9 5.8 5.7 6.2 6.3 6.1 5.7 5.6 5.8
Mean result per chemical: [5.9  5.93 5.94]


In [86]:
# 18. Determine which trial had the highest deviation from the mean for each sample.

deviation = np.abs(results - mean_results)
max_deviation_trials = np.argmax(deviation, axis=0)
print("Trial with highest deviation for each chemical:", max_deviation_trials)

Trial with highest deviation for each chemical: [0 8 6]


In [87]:
# 19. A hospital records 3 vital signs for 2 patients over 5 days. Store this in a 3D array and retrieve the vitals for the first patient on day 4.

print("Enter vitals for 2 patients over 5 days (3 vitals per day, total 30 values per patient):")
vitals_input = list(map(int, input().split()))
vitals = np.array(vitals_input).reshape(2, 5, 3)
print("Vitals for patient 1 on day 4:", vitals[0, 3])

Enter vitals for 2 patients over 5 days (3 vitals per day, total 30 values per patient):
120 80 70 122 82 72 119 78 68 121 79 71 118 77 69   130 85 75 128 83 74 129 84 76 131 86 77 127 82 73
Vitals for patient 1 on day 4: [121  79  71]


In [89]:
# 20. Find the mode of a particular vital sign for one patient across all days.

vital_sign_values = vitals[0, :, 1]
values, counts = np.unique(vital_sign_values, return_counts=True)
mode_value = values[np.argmax(counts)]
print("Mode of vital sign:", mode_value)

Mode of vital sign: 77
